MERGE INTO Manufacturers AS Target

USING
(
    VALUES
    (
        'MFR001',
        'Pharma Manufacturer 1',
        'Contact Person 1',
        'manufacturer1@pharma.com',
        '9876500001',
        'Plot 1, Pharma Industrial Area',
        'Phase I',
        'Mumbai',
        'Maharashtra',
        'India',
        '500001',
        'https://www.manufacturer1.com',
        TRUE
    ),
    (
        'MFR002',
        'Pharma Manufacturer 2',
        'Contact Person 2',
        'manufacturer2@pharma.com',
        '9876500002',
        'Plot 2, Pharma Industrial Area',
        'Phase I',
        'Hyderabad',
        'Telangana',
        'India',
        '500002',
        'https://www.manufacturer2.com',
        TRUE
    ),
    (
        'MFR003',
        'Pharma Manufacturer 3',
        'Contact Person 3',
        'manufacturer3@pharma.com',
        '9876500003',
        'Plot 3, Pharma Industrial Area',
        'Phase I',
        'Ahmedabad',
        'Gujarat',
        'India',
        '500003',
        'https://www.manufacturer3.com',
        TRUE
    ),
    (
        'MFR004',
        'Pharma Manufacturer 4',
        'Contact Person 4',
        'manufacturer4@pharma.com',
        '9876500004',
        'Plot 4, Pharma Industrial Area',
        'Phase I',
        'Bengaluru',
        'Karnataka',
        'India',
        '500004',
        'https://www.manufacturer4.com',
        TRUE
    ),
    (
        'MFR005',
        'Pharma Manufacturer 5',
        'Contact Person 5',
        'manufacturer5@pharma.com',
        '9876500005',
        'Plot 5, Pharma Industrial Area',
        'Phase I',
        'Chennai',
        'Tamil Nadu',
        'India',
        '500005',
        'https://www.manufacturer5.com',
        TRUE
    ),
    (
        'MFR006',
        'Pharma Manufacturer 6',
        'Contact Person 6',
        'manufacturer6@pharma.com',
        '9876500006',
        'Plot 6, Pharma Industrial Area',
        'Phase I',
        'Pune',
        'Maharashtra',
        'India',
        '500006',
        'https://www.manufacturer6.com',
        TRUE
    ),
    (
        'MFR007',
        'Pharma Manufacturer 7',
        'Contact Person 7',
        'manufacturer7@pharma.com',
        '9876500007',
        'Plot 7, Pharma Industrial Area',
        'Phase I',
        'Visakhapatnam',
        'Andhra Pradesh',
        'India',
        '500007',
        'https://www.manufacturer7.com',
        TRUE
    ),
    (
        'MFR008',
        'Pharma Manufacturer 8',
        'Contact Person 8',
        'manufacturer8@pharma.com',
        '9876500008',
        'Plot 8, Pharma Industrial Area',
        'Phase I',
        'Vijayawada',
        'Andhra Pradesh',
        'India',
        '500008',
        'https://www.manufacturer8.com',
        TRUE
    ),
    (
        'MFR009',
        'Pharma Manufacturer 9',
        'Contact Person 9',
        'manufacturer9@pharma.com',
        '9876500009',
        'Plot 9, Pharma Industrial Area',
        'Phase I',
        'Noida',
        'Uttar Pradesh',
        'India',
        '500009',
        'https://www.manufacturer9.com',
        TRUE
    ),
    (
        'MFR010',
        'Pharma Manufacturer 10',
        'Contact Person 10',
        'manufacturer10@pharma.com',
        '9876500010',
        'Plot 10, Pharma Industrial Area',
        'Phase I',
        'Kolkata',
        'West Bengal',
        'India',
        '500010',
        'https://www.manufacturer10.com',
        TRUE
    ),
    (
        'MFR011',
        'Pharma Manufacturer 11',
        'Contact Person 11',
        'manufacturer11@pharma.com',
        '9876500011',
        'Plot 11, Pharma Industrial Area',
        'Phase I',
        'Mumbai',
        'Maharashtra',
        'India',
        '500011',
        'https://www.manufacturer11.com',
        TRUE
    ),
    (
        'MFR012',
        'Pharma Manufacturer 12',
        'Contact Person 12',
        'manufacturer12@pharma.com',
        '9876500012',
        'Plot 12, Pharma Industrial Area',
        'Phase I',
        'Hyderabad',
        'Telangana',
        'India',
        '500012',
        'https://www.manufacturer12.com',
        TRUE
    ),
    (
        'MFR013',
        'Pharma Manufacturer 13',
        'Contact Person 13',
        'manufacturer13@pharma.com',
        '9876500013',
        'Plot 13, Pharma Industrial Area',
        'Phase I',
        'Ahmedabad',
        'Gujarat',
        'India',
        '500013',
        'https://www.manufacturer13.com',
        TRUE
    ),
    (
        'MFR014',
        'Pharma Manufacturer 14',
        'Contact Person 14',
        'manufacturer14@pharma.com',
        '9876500014',
        'Plot 14, Pharma Industrial Area',
        'Phase I',
        'Bengaluru',
        'Karnataka',
        'India',
        '500014',
        'https://www.manufacturer14.com',
        TRUE
    ),
    (
        'MFR015',
        'Pharma Manufacturer 15',
        'Contact Person 15',
        'manufacturer15@pharma.com',
        '9876500015',
        'Plot 15, Pharma Industrial Area',
        'Phase I',
        'Chennai',
        'Tamil Nadu',
        'India',
        '500015',
        'https://www.manufacturer15.com',
        TRUE
    ),
    (
        'MFR016',
        'Pharma Manufacturer 16',
        'Contact Person 16',
        'manufacturer16@pharma.com',
        '9876500016',
        'Plot 16, Pharma Industrial Area',
        'Phase I',
        'Pune',
        'Maharashtra',
        'India',
        '500016',
        'https://www.manufacturer16.com',
        TRUE
    ),
    (
        'MFR017',
        'Pharma Manufacturer 17',
        'Contact Person 17',
        'manufacturer17@pharma.com',
        '9876500017',
        'Plot 17, Pharma Industrial Area',
        'Phase I',
        'Visakhapatnam',
        'Andhra Pradesh',
        'India',
        '500017',
        'https://www.manufacturer17.com',
        TRUE
    ),
    (
        'MFR018',
        'Pharma Manufacturer 18',
        'Contact Person 18',
        'manufacturer18@pharma.com',
        '9876500018',
        'Plot 18, Pharma Industrial Area',
        'Phase I',
        'Vijayawada',
        'Andhra Pradesh',
        'India',
        '500018',
        'https://www.manufacturer18.com',
        TRUE
    ),
    (
        'MFR019',
        'Pharma Manufacturer 19',
        'Contact Person 19',
        'manufacturer19@pharma.com',
        '9876500019',
        'Plot 19, Pharma Industrial Area',
        'Phase I',
        'Noida',
        'Uttar Pradesh',
        'India',
        '500019',
        'https://www.manufacturer19.com',
        TRUE
    ),
    (
        'MFR020',
        'Pharma Manufacturer 20',
        'Contact Person 20',
        'manufacturer20@pharma.com',
        '9876500020',
        'Plot 20, Pharma Industrial Area',
        'Phase I',
        'Kolkata',
        'West Bengal',
        'India',
        '500020',
        'https://www.manufacturer20.com',
        TRUE
    ),
    (
        'MFR021',
        'Pharma Manufacturer 21',
        'Contact Person 21',
        'manufacturer21@pharma.com',
        '9876500021',
        'Plot 21, Pharma Industrial Area',
        'Phase I',
        'Mumbai',
        'Maharashtra',
        'India',
        '500021',
        'https://www.manufacturer21.com',
        TRUE
    ),
    (
        'MFR022',
        'Pharma Manufacturer 22',
        'Contact Person 22',
        'manufacturer22@pharma.com',
        '9876500022',
        'Plot 22, Pharma Industrial Area',
        'Phase I',
        'Hyderabad',
        'Telangana',
        'India',
        '500022',
        'https://www.manufacturer22.com',
        TRUE
    ),
    (
        'MFR023',
        'Pharma Manufacturer 23',
        'Contact Person 23',
        'manufacturer23@pharma.com',
        '9876500023',
        'Plot 23, Pharma Industrial Area',
        'Phase I',
        'Ahmedabad',
        'Gujarat',
        'India',
        '500023',
        'https://www.manufacturer23.com',
        TRUE
    ),
    (
        'MFR024',
        'Pharma Manufacturer 24',
        'Contact Person 24',
        'manufacturer24@pharma.com',
        '9876500024',
        'Plot 24, Pharma Industrial Area',
        'Phase I',
        'Bengaluru',
        'Karnataka',
        'India',
        '500024',
        'https://www.manufacturer24.com',
        TRUE
    ),
    (
        'MFR025',
        'Pharma Manufacturer 25',
        'Contact Person 25',
        'manufacturer25@pharma.com',
        '9876500025',
        'Plot 25, Pharma Industrial Area',
        'Phase I',
        'Chennai',
        'Tamil Nadu',
        'India',
        '500025',
        'https://www.manufacturer25.com',
        TRUE
    ),
    (
        'MFR026',
        'Pharma Manufacturer 26',
        'Contact Person 26',
        'manufacturer26@pharma.com',
        '9876500026',
        'Plot 26, Pharma Industrial Area',
        'Phase I',
        'Pune',
        'Maharashtra',
        'India',
        '500026',
        'https://www.manufacturer26.com',
        TRUE
    ),
    (
        'MFR027',
        'Pharma Manufacturer 27',
        'Contact Person 27',
        'manufacturer27@pharma.com',
        '9876500027',
        'Plot 27, Pharma Industrial Area',
        'Phase I',
        'Visakhapatnam',
        'Andhra Pradesh',
        'India',
        '500027',
        'https://www.manufacturer27.com',
        TRUE
    ),
    (
        'MFR028',
        'Pharma Manufacturer 28',
        'Contact Person 28',
        'manufacturer28@pharma.com',
        '9876500028',
        'Plot 28, Pharma Industrial Area',
        'Phase I',
        'Vijayawada',
        'Andhra Pradesh',
        'India',
        '500028',
        'https://www.manufacturer28.com',
        TRUE
    ),
    (
        'MFR029',
        'Pharma Manufacturer 29',
        'Contact Person 29',
        'manufacturer29@pharma.com',
        '9876500029',
        'Plot 29, Pharma Industrial Area',
        'Phase I',
        'Noida',
        'Uttar Pradesh',
        'India',
        '500029',
        'https://www.manufacturer29.com',
        TRUE
    ),
    (
        'MFR030',
        'Pharma Manufacturer 30',
        'Contact Person 30',
        'manufacturer30@pharma.com',
        '9876500030',
        'Plot 30, Pharma Industrial Area',
        'Phase I',
        'Kolkata',
        'West Bengal',
        'India',
        '500030',
        'https://www.manufacturer30.com',
        TRUE
    ),
    (
        'MFR031',
        'Pharma Manufacturer 31',
        'Contact Person 31',
        'manufacturer31@pharma.com',
        '9876500031',
        'Plot 31, Pharma Industrial Area',
        'Phase I',
        'Mumbai',
        'Maharashtra',
        'India',
        '500031',
        'https://www.manufacturer31.com',
        TRUE
    ),
    (
        'MFR032',
        'Pharma Manufacturer 32',
        'Contact Person 32',
        'manufacturer32@pharma.com',
        '9876500032',
        'Plot 32, Pharma Industrial Area',
        'Phase I',
        'Hyderabad',
        'Telangana',
        'India',
        '500032',
        'https://www.manufacturer32.com',
        TRUE
    ),
    (
        'MFR033',
        'Pharma Manufacturer 33',
        'Contact Person 33',
        'manufacturer33@pharma.com',
        '9876500033',
        'Plot 33, Pharma Industrial Area',
        'Phase I',
        'Ahmedabad',
        'Gujarat',
        'India',
        '500033',
        'https://www.manufacturer33.com',
        TRUE
    ),
    (
        'MFR034',
        'Pharma Manufacturer 34',
        'Contact Person 34',
        'manufacturer34@pharma.com',
        '9876500034',
        'Plot 34, Pharma Industrial Area',
        'Phase I',
        'Bengaluru',
        'Karnataka',
        'India',
        '500034',
        'https://www.manufacturer34.com',
        TRUE
    ),
    (
        'MFR035',
        'Pharma Manufacturer 35',
        'Contact Person 35',
        'manufacturer35@pharma.com',
        '9876500035',
        'Plot 35, Pharma Industrial Area',
        'Phase I',
        'Chennai',
        'Tamil Nadu',
        'India',
        '500035',
        'https://www.manufacturer35.com',
        TRUE
    ),
    (
        'MFR036',
        'Pharma Manufacturer 36',
        'Contact Person 36',
        'manufacturer36@pharma.com',
        '9876500036',
        'Plot 36, Pharma Industrial Area',
        'Phase I',
        'Pune',
        'Maharashtra',
        'India',
        '500036',
        'https://www.manufacturer36.com',
        TRUE
    ),
    (
        'MFR037',
        'Pharma Manufacturer 37',
        'Contact Person 37',
        'manufacturer37@pharma.com',
        '9876500037',
        'Plot 37, Pharma Industrial Area',
        'Phase I',
        'Visakhapatnam',
        'Andhra Pradesh',
        'India',
        '500037',
        'https://www.manufacturer37.com',
        TRUE
    ),
    (
        'MFR038',
        'Pharma Manufacturer 38',
        'Contact Person 38',
        'manufacturer38@pharma.com',
        '9876500038',
        'Plot 38, Pharma Industrial Area',
        'Phase I',
        'Vijayawada',
        'Andhra Pradesh',
        'India',
        '500038',
        'https://www.manufacturer38.com',
        TRUE
    ),
    (
        'MFR039',
        'Pharma Manufacturer 39',
        'Contact Person 39',
        'manufacturer39@pharma.com',
        '9876500039',
        'Plot 39, Pharma Industrial Area',
        'Phase I',
        'Noida',
        'Uttar Pradesh',
        'India',
        '500039',
        'https://www.manufacturer39.com',
        TRUE
    ),
    (
        'MFR040',
        'Pharma Manufacturer 40',
        'Contact Person 40',
        'manufacturer40@pharma.com',
        '9876500040',
        'Plot 40, Pharma Industrial Area',
        'Phase I',
        'Kolkata',
        'West Bengal',
        'India',
        '500040',
        'https://www.manufacturer40.com',
        TRUE
    ),
    (
        'MFR041',
        'Pharma Manufacturer 41',
        'Contact Person 41',
        'manufacturer41@pharma.com',
        '9876500041',
        'Plot 41, Pharma Industrial Area',
        'Phase I',
        'Mumbai',
        'Maharashtra',
        'India',
        '500041',
        'https://www.manufacturer41.com',
        TRUE
    ),
    (
        'MFR042',
        'Pharma Manufacturer 42',
        'Contact Person 42',
        'manufacturer42@pharma.com',
        '9876500042',
        'Plot 42, Pharma Industrial Area',
        'Phase I',
        'Hyderabad',
        'Telangana',
        'India',
        '500042',
        'https://www.manufacturer42.com',
        TRUE
    ),
    (
        'MFR043',
        'Pharma Manufacturer 43',
        'Contact Person 43',
        'manufacturer43@pharma.com',
        '9876500043',
        'Plot 43, Pharma Industrial Area',
        'Phase I',
        'Ahmedabad',
        'Gujarat',
        'India',
        '500043',
        'https://www.manufacturer43.com',
        TRUE
    ),
    (
        'MFR044',
        'Pharma Manufacturer 44',
        'Contact Person 44',
        'manufacturer44@pharma.com',
        '9876500044',
        'Plot 44, Pharma Industrial Area',
        'Phase I',
        'Bengaluru',
        'Karnataka',
        'India',
        '500044',
        'https://www.manufacturer44.com',
        TRUE
    ),
    (
        'MFR045',
        'Pharma Manufacturer 45',
        'Contact Person 45',
        'manufacturer45@pharma.com',
        '9876500045',
        'Plot 45, Pharma Industrial Area',
        'Phase I',
        'Chennai',
        'Tamil Nadu',
        'India',
        '500045',
        'https://www.manufacturer45.com',
        TRUE
    ),
    (
        'MFR046',
        'Pharma Manufacturer 46',
        'Contact Person 46',
        'manufacturer46@pharma.com',
        '9876500046',
        'Plot 46, Pharma Industrial Area',
        'Phase I',
        'Pune',
        'Maharashtra',
        'India',
        '500046',
        'https://www.manufacturer46.com',
        TRUE
    ),
    (
        'MFR047',
        'Pharma Manufacturer 47',
        'Contact Person 47',
        'manufacturer47@pharma.com',
        '9876500047',
        'Plot 47, Pharma Industrial Area',
        'Phase I',
        'Visakhapatnam',
        'Andhra Pradesh',
        'India',
        '500047',
        'https://www.manufacturer47.com',
        TRUE
    ),
    (
        'MFR048',
        'Pharma Manufacturer 48',
        'Contact Person 48',
        'manufacturer48@pharma.com',
        '9876500048',
        'Plot 48, Pharma Industrial Area',
        'Phase I',
        'Vijayawada',
        'Andhra Pradesh',
        'India',
        '500048',
        'https://www.manufacturer48.com',
        TRUE
    ),
    (
        'MFR049',
        'Pharma Manufacturer 49',
        'Contact Person 49',
        'manufacturer49@pharma.com',
        '9876500049',
        'Plot 49, Pharma Industrial Area',
        'Phase I',
        'Noida',
        'Uttar Pradesh',
        'India',
        '500049',
        'https://www.manufacturer49.com',
        TRUE
    ),
    (
        'MFR050',
        'Pharma Manufacturer 50',
        'Contact Person 50',
        'manufacturer50@pharma.com',
        '9876500050',
        'Plot 50, Pharma Industrial Area',
        'Phase I',
        'Kolkata',
        'West Bengal',
        'India',
        '500050',
        'https://www.manufacturer50.com',
        TRUE
    ),
    (
        'MFR051',
        'Pharma Manufacturer 51',
        'Contact Person 51',
        'manufacturer51@pharma.com',
        '9876500051',
        'Plot 51, Pharma Industrial Area',
        'Phase I',
        'Mumbai',
        'Maharashtra',
        'India',
        '500051',
        'https://www.manufacturer51.com',
        TRUE
    ),
    (
        'MFR052',
        'Pharma Manufacturer 52',
        'Contact Person 52',
        'manufacturer52@pharma.com',
        '9876500052',
        'Plot 52, Pharma Industrial Area',
        'Phase I',
        'Hyderabad',
        'Telangana',
        'India',
        '500052',
        'https://www.manufacturer52.com',
        TRUE
    ),
    (
        'MFR053',
        'Pharma Manufacturer 53',
        'Contact Person 53',
        'manufacturer53@pharma.com',
        '9876500053',
        'Plot 53, Pharma Industrial Area',
        'Phase I',
        'Ahmedabad',
        'Gujarat',
        'India',
        '500053',
        'https://www.manufacturer53.com',
        TRUE
    ),
    (
        'MFR054',
        'Pharma Manufacturer 54',
        'Contact Person 54',
        'manufacturer54@pharma.com',
        '9876500054',
        'Plot 54, Pharma Industrial Area',
        'Phase I',
        'Bengaluru',
        'Karnataka',
        'India',
        '500054',
        'https://www.manufacturer54.com',
        TRUE
    ),
    (
        'MFR055',
        'Pharma Manufacturer 55',
        'Contact Person 55',
        'manufacturer55@pharma.com',
        '9876500055',
        'Plot 55, Pharma Industrial Area',
        'Phase I',
        'Chennai',
        'Tamil Nadu',
        'India',
        '500055',
        'https://www.manufacturer55.com',
        TRUE
    ),
    (
        'MFR056',
        'Pharma Manufacturer 56',
        'Contact Person 56',
        'manufacturer56@pharma.com',
        '9876500056',
        'Plot 56, Pharma Industrial Area',
        'Phase I',
        'Pune',
        'Maharashtra',
        'India',
        '500056',
        'https://www.manufacturer56.com',
        TRUE
    ),
    (
        'MFR057',
        'Pharma Manufacturer 57',
        'Contact Person 57',
        'manufacturer57@pharma.com',
        '9876500057',
        'Plot 57, Pharma Industrial Area',
        'Phase I',
        'Visakhapatnam',
        'Andhra Pradesh',
        'India',
        '500057',
        'https://www.manufacturer57.com',
        TRUE
    ),
    (
        'MFR058',
        'Pharma Manufacturer 58',
        'Contact Person 58',
        'manufacturer58@pharma.com',
        '9876500058',
        'Plot 58, Pharma Industrial Area',
        'Phase I',
        'Vijayawada',
        'Andhra Pradesh',
        'India',
        '500058',
        'https://www.manufacturer58.com',
        TRUE
    ),
    (
        'MFR059',
        'Pharma Manufacturer 59',
        'Contact Person 59',
        'manufacturer59@pharma.com',
        '9876500059',
        'Plot 59, Pharma Industrial Area',
        'Phase I',
        'Noida',
        'Uttar Pradesh',
        'India',
        '500059',
        'https://www.manufacturer59.com',
        TRUE
    ),
    (
        'MFR060',
        'Pharma Manufacturer 60',
        'Contact Person 60',
        'manufacturer60@pharma.com',
        '9876500060',
        'Plot 60, Pharma Industrial Area',
        'Phase I',
        'Kolkata',
        'West Bengal',
        'India',
        '500060',
        'https://www.manufacturer60.com',
        TRUE
    ),
    (
        'MFR061',
        'Pharma Manufacturer 61',
        'Contact Person 61',
        'manufacturer61@pharma.com',
        '9876500061',
        'Plot 61, Pharma Industrial Area',
        'Phase I',
        'Mumbai',
        'Maharashtra',
        'India',
        '500061',
        'https://www.manufacturer61.com',
        TRUE
    ),
    (
        'MFR062',
        'Pharma Manufacturer 62',
        'Contact Person 62',
        'manufacturer62@pharma.com',
        '9876500062',
        'Plot 62, Pharma Industrial Area',
        'Phase I',
        'Hyderabad',
        'Telangana',
        'India',
        '500062',
        'https://www.manufacturer62.com',
        TRUE
    ),
    (
        'MFR063',
        'Pharma Manufacturer 63',
        'Contact Person 63',
        'manufacturer63@pharma.com',
        '9876500063',
        'Plot 63, Pharma Industrial Area',
        'Phase I',
        'Ahmedabad',
        'Gujarat',
        'India',
        '500063',
        'https://www.manufacturer63.com',
        TRUE
    ),
    (
        'MFR064',
        'Pharma Manufacturer 64',
        'Contact Person 64',
        'manufacturer64@pharma.com',
        '9876500064',
        'Plot 64, Pharma Industrial Area',
        'Phase I',
        'Bengaluru',
        'Karnataka',
        'India',
        '500064',
        'https://www.manufacturer64.com',
        TRUE
    ),
    (
        'MFR065',
        'Pharma Manufacturer 65',
        'Contact Person 65',
        'manufacturer65@pharma.com',
        '9876500065',
        'Plot 65, Pharma Industrial Area',
        'Phase I',
        'Chennai',
        'Tamil Nadu',
        'India',
        '500065',
        'https://www.manufacturer65.com',
        TRUE
    ),
    (
        'MFR066',
        'Pharma Manufacturer 66',
        'Contact Person 66',
        'manufacturer66@pharma.com',
        '9876500066',
        'Plot 66, Pharma Industrial Area',
        'Phase I',
        'Pune',
        'Maharashtra',
        'India',
        '500066',
        'https://www.manufacturer66.com',
        TRUE
    ),
    (
        'MFR067',
        'Pharma Manufacturer 67',
        'Contact Person 67',
        'manufacturer67@pharma.com',
        '9876500067',
        'Plot 67, Pharma Industrial Area',
        'Phase I',
        'Visakhapatnam',
        'Andhra Pradesh',
        'India',
        '500067',
        'https://www.manufacturer67.com',
        TRUE
    ),
    (
        'MFR068',
        'Pharma Manufacturer 68',
        'Contact Person 68',
        'manufacturer68@pharma.com',
        '9876500068',
        'Plot 68, Pharma Industrial Area',
        'Phase I',
        'Vijayawada',
        'Andhra Pradesh',
        'India',
        '500068',
        'https://www.manufacturer68.com',
        TRUE
    ),
    (
        'MFR069',
        'Pharma Manufacturer 69',
        'Contact Person 69',
        'manufacturer69@pharma.com',
        '9876500069',
        'Plot 69, Pharma Industrial Area',
        'Phase I',
        'Noida',
        'Uttar Pradesh',
        'India',
        '500069',
        'https://www.manufacturer69.com',
        TRUE
    ),
    (
        'MFR070',
        'Pharma Manufacturer 70',
        'Contact Person 70',
        'manufacturer70@pharma.com',
        '9876500070',
        'Plot 70, Pharma Industrial Area',
        'Phase I',
        'Kolkata',
        'West Bengal',
        'India',
        '500070',
        'https://www.manufacturer70.com',
        TRUE
    ),
    (
        'MFR071',
        'Pharma Manufacturer 71',
        'Contact Person 71',
        'manufacturer71@pharma.com',
        '9876500071',
        'Plot 71, Pharma Industrial Area',
        'Phase I',
        'Mumbai',
        'Maharashtra',
        'India',
        '500071',
        'https://www.manufacturer71.com',
        TRUE
    ),
    (
        'MFR072',
        'Pharma Manufacturer 72',
        'Contact Person 72',
        'manufacturer72@pharma.com',
        '9876500072',
        'Plot 72, Pharma Industrial Area',
        'Phase I',
        'Hyderabad',
        'Telangana',
        'India',
        '500072',
        'https://www.manufacturer72.com',
        TRUE
    ),
    (
        'MFR073',
        'Pharma Manufacturer 73',
        'Contact Person 73',
        'manufacturer73@pharma.com',
        '9876500073',
        'Plot 73, Pharma Industrial Area',
        'Phase I',
        'Ahmedabad',
        'Gujarat',
        'India',
        '500073',
        'https://www.manufacturer73.com',
        TRUE
    ),
    (
        'MFR074',
        'Pharma Manufacturer 74',
        'Contact Person 74',
        'manufacturer74@pharma.com',
        '9876500074',
        'Plot 74, Pharma Industrial Area',
        'Phase I',
        'Bengaluru',
        'Karnataka',
        'India',
        '500074',
        'https://www.manufacturer74.com',
        TRUE
    ),
    (
        'MFR075',
        'Pharma Manufacturer 75',
        'Contact Person 75',
        'manufacturer75@pharma.com',
        '9876500075',
        'Plot 75, Pharma Industrial Area',
        'Phase I',
        'Chennai',
        'Tamil Nadu',
        'India',
        '500075',
        'https://www.manufacturer75.com',
        TRUE
    ),
    (
        'MFR076',
        'Pharma Manufacturer 76',
        'Contact Person 76',
        'manufacturer76@pharma.com',
        '9876500076',
        'Plot 76, Pharma Industrial Area',
        'Phase I',
        'Pune',
        'Maharashtra',
        'India',
        '500076',
        'https://www.manufacturer76.com',
        TRUE
    ),
    (
        'MFR077',
        'Pharma Manufacturer 77',
        'Contact Person 77',
        'manufacturer77@pharma.com',
        '9876500077',
        'Plot 77, Pharma Industrial Area',
        'Phase I',
        'Visakhapatnam',
        'Andhra Pradesh',
        'India',
        '500077',
        'https://www.manufacturer77.com',
        TRUE
    ),
    (
        'MFR078',
        'Pharma Manufacturer 78',
        'Contact Person 78',
        'manufacturer78@pharma.com',
        '9876500078',
        'Plot 78, Pharma Industrial Area',
        'Phase I',
        'Vijayawada',
        'Andhra Pradesh',
        'India',
        '500078',
        'https://www.manufacturer78.com',
        TRUE
    ),
    (
        'MFR079',
        'Pharma Manufacturer 79',
        'Contact Person 79',
        'manufacturer79@pharma.com',
        '9876500079',
        'Plot 79, Pharma Industrial Area',
        'Phase I',
        'Noida',
        'Uttar Pradesh',
        'India',
        '500079',
        'https://www.manufacturer79.com',
        TRUE
    ),
    (
        'MFR080',
        'Pharma Manufacturer 80',
        'Contact Person 80',
        'manufacturer80@pharma.com',
        '9876500080',
        'Plot 80, Pharma Industrial Area',
        'Phase I',
        'Kolkata',
        'West Bengal',
        'India',
        '500080',
        'https://www.manufacturer80.com',
        TRUE
    ),
    (
        'MFR081',
        'Pharma Manufacturer 81',
        'Contact Person 81',
        'manufacturer81@pharma.com',
        '9876500081',
        'Plot 81, Pharma Industrial Area',
        'Phase I',
        'Mumbai',
        'Maharashtra',
        'India',
        '500081',
        'https://www.manufacturer81.com',
        TRUE
    ),
    (
        'MFR082',
        'Pharma Manufacturer 82',
        'Contact Person 82',
        'manufacturer82@pharma.com',
        '9876500082',
        'Plot 82, Pharma Industrial Area',
        'Phase I',
        'Hyderabad',
        'Telangana',
        'India',
        '500082',
        'https://www.manufacturer82.com',
        TRUE
    ),
    (
        'MFR083',
        'Pharma Manufacturer 83',
        'Contact Person 83',
        'manufacturer83@pharma.com',
        '9876500083',
        'Plot 83, Pharma Industrial Area',
        'Phase I',
        'Ahmedabad',
        'Gujarat',
        'India',
        '500083',
        'https://www.manufacturer83.com',
        TRUE
    ),
    (
        'MFR084',
        'Pharma Manufacturer 84',
        'Contact Person 84',
        'manufacturer84@pharma.com',
        '9876500084',
        'Plot 84, Pharma Industrial Area',
        'Phase I',
        'Bengaluru',
        'Karnataka',
        'India',
        '500084',
        'https://www.manufacturer84.com',
        TRUE
    ),
    (
        'MFR085',
        'Pharma Manufacturer 85',
        'Contact Person 85',
        'manufacturer85@pharma.com',
        '9876500085',
        'Plot 85, Pharma Industrial Area',
        'Phase I',
        'Chennai',
        'Tamil Nadu',
        'India',
        '500085',
        'https://www.manufacturer85.com',
        TRUE
    ),
    (
        'MFR086',
        'Pharma Manufacturer 86',
        'Contact Person 86',
        'manufacturer86@pharma.com',
        '9876500086',
        'Plot 86, Pharma Industrial Area',
        'Phase I',
        'Pune',
        'Maharashtra',
        'India',
        '500086',
        'https://www.manufacturer86.com',
        TRUE
    ),
    (
        'MFR087',
        'Pharma Manufacturer 87',
        'Contact Person 87',
        'manufacturer87@pharma.com',
        '9876500087',
        'Plot 87, Pharma Industrial Area',
        'Phase I',
        'Visakhapatnam',
        'Andhra Pradesh',
        'India',
        '500087',
        'https://www.manufacturer87.com',
        TRUE
    ),
    (
        'MFR088',
        'Pharma Manufacturer 88',
        'Contact Person 88',
        'manufacturer88@pharma.com',
        '9876500088',
        'Plot 88, Pharma Industrial Area',
        'Phase I',
        'Vijayawada',
        'Andhra Pradesh',
        'India',
        '500088',
        'https://www.manufacturer88.com',
        TRUE
    ),
    (
        'MFR089',
        'Pharma Manufacturer 89',
        'Contact Person 89',
        'manufacturer89@pharma.com',
        '9876500089',
        'Plot 89, Pharma Industrial Area',
        'Phase I',
        'Noida',
        'Uttar Pradesh',
        'India',
        '500089',
        'https://www.manufacturer89.com',
        TRUE
    ),
    (
        'MFR090',
        'Pharma Manufacturer 90',
        'Contact Person 90',
        'manufacturer90@pharma.com',
        '9876500090',
        'Plot 90, Pharma Industrial Area',
        'Phase I',
        'Kolkata',
        'West Bengal',
        'India',
        '500090',
        'https://www.manufacturer90.com',
        TRUE
    ),
    (
        'MFR091',
        'Pharma Manufacturer 91',
        'Contact Person 91',
        'manufacturer91@pharma.com',
        '9876500091',
        'Plot 91, Pharma Industrial Area',
        'Phase I',
        'Mumbai',
        'Maharashtra',
        'India',
        '500091',
        'https://www.manufacturer91.com',
        TRUE
    ),
    (
        'MFR092',
        'Pharma Manufacturer 92',
        'Contact Person 92',
        'manufacturer92@pharma.com',
        '9876500092',
        'Plot 92, Pharma Industrial Area',
        'Phase I',
        'Hyderabad',
        'Telangana',
        'India',
        '500092',
        'https://www.manufacturer92.com',
        TRUE
    ),
    (
        'MFR093',
        'Pharma Manufacturer 93',
        'Contact Person 93',
        'manufacturer93@pharma.com',
        '9876500093',
        'Plot 93, Pharma Industrial Area',
        'Phase I',
        'Ahmedabad',
        'Gujarat',
        'India',
        '500093',
        'https://www.manufacturer93.com',
        TRUE
    ),
    (
        'MFR094',
        'Pharma Manufacturer 94',
        'Contact Person 94',
        'manufacturer94@pharma.com',
        '9876500094',
        'Plot 94, Pharma Industrial Area',
        'Phase I',
        'Bengaluru',
        'Karnataka',
        'India',
        '500094',
        'https://www.manufacturer94.com',
        TRUE
    ),
    (
        'MFR095',
        'Pharma Manufacturer 95',
        'Contact Person 95',
        'manufacturer95@pharma.com',
        '9876500095',
        'Plot 95, Pharma Industrial Area',
        'Phase I',
        'Chennai',
        'Tamil Nadu',
        'India',
        '500095',
        'https://www.manufacturer95.com',
        TRUE
    ),
    (
        'MFR096',
        'Pharma Manufacturer 96',
        'Contact Person 96',
        'manufacturer96@pharma.com',
        '9876500096',
        'Plot 96, Pharma Industrial Area',
        'Phase I',
        'Pune',
        'Maharashtra',
        'India',
        '500096',
        'https://www.manufacturer96.com',
        TRUE
    ),
    (
        'MFR097',
        'Pharma Manufacturer 97',
        'Contact Person 97',
        'manufacturer97@pharma.com',
        '9876500097',
        'Plot 97, Pharma Industrial Area',
        'Phase I',
        'Visakhapatnam',
        'Andhra Pradesh',
        'India',
        '500097',
        'https://www.manufacturer97.com',
        TRUE
    ),
    (
        'MFR098',
        'Pharma Manufacturer 98',
        'Contact Person 98',
        'manufacturer98@pharma.com',
        '9876500098',
        'Plot 98, Pharma Industrial Area',
        'Phase I',
        'Vijayawada',
        'Andhra Pradesh',
        'India',
        '500098',
        'https://www.manufacturer98.com',
        TRUE
    ),
    (
        'MFR099',
        'Pharma Manufacturer 99',
        'Contact Person 99',
        'manufacturer99@pharma.com',
        '9876500099',
        'Plot 99, Pharma Industrial Area',
        'Phase I',
        'Noida',
        'Uttar Pradesh',
        'India',
        '500099',
        'https://www.manufacturer99.com',
        TRUE
    ),
    (
        'MFR100',
        'Pharma Manufacturer 100',
        'Contact Person 100',
        'manufacturer100@pharma.com',
        '9876500100',
        'Plot 100, Pharma Industrial Area',
        'Phase I',
        'Kolkata',
        'West Bengal',
        'India',
        '500100',
        'https://www.manufacturer100.com',
        TRUE
    )

) AS Source
(
    ManufacturerCode,
    ManufacturerName,
    ContactPerson,
    Email,
    Phone,
    AddressLine1,
    AddressLine2,
    City,
    State,
    Country,
    PostalCode,
    Website,
    IsActive
)

ON Target.ManufacturerCode = Source.ManufacturerCode

WHEN MATCHED THEN
UPDATE SET
    ManufacturerName = Source.ManufacturerName,
    ContactPerson = Source.ContactPerson,
    Email = Source.Email,
    Phone = Source.Phone,
    AddressLine1 = Source.AddressLine1,
    AddressLine2 = Source.AddressLine2,
    City = Source.City,
    State = Source.State,
    Country = Source.Country,
    PostalCode = Source.PostalCode,
    Website = Source.Website,
    IsActive = Source.IsActive,
    ModifiedOn = CURRENT_TIMESTAMP

WHEN NOT MATCHED THEN
INSERT
(
    ManufacturerCode,
    ManufacturerName,
    ContactPerson,
    Email,
    Phone,
    AddressLine1,
    AddressLine2,
    City,
    State,
    Country,
    PostalCode,
    Website,
    IsActive,
    CreatedOn
)
VALUES
(
    Source.ManufacturerCode,
    Source.ManufacturerName,
    Source.ContactPerson,
    Source.Email,
    Source.Phone,
    Source.AddressLine1,
    Source.AddressLine2,
    Source.City,
    Source.State,
    Source.Country,
    Source.PostalCode,
    Source.Website,
    Source.IsActive,
    CURRENT_TIMESTAMP
);

