MERGE INTO distributors AS Target

USING
(
    VALUES
    (
        'DIST001',
        'ABC Pharma Distributors',
        'REG001',
        'DL-TG-001',
        '36ABCDE1234F1Z5',
        'Ravi Kumar',
        'abcpharma@gmail.com',
        '9876543210',
        '9876543211',
        'Road No.1',
        'Madhapur',
        'Hyderabad',
        'Telangana',
        'India',
        '500081',
        'https://www.abcpharma.com',
        '030f2b9b-1f56-4482-b2f3-059ea92f2160',
        true  
    ),
    (
        'DIST002',
        'XYZ Medical Agencies',
        'REG002',
        'DL-TG-002',
        '36XYZAB1234F1Z6',
        'Ramesh Kumar',
        'xyzmedical@gmail.com',
        '9876543212',
        '9876543213',
        'MG Road',
        'Hanamkonda',
        'Warangal',
        'Telangana',
        'India',
        '506001',
        'https://www.xyzmedical.com',
        '1a2b3c4d-5e6f-7890-abcd-ef1234567890',
        true
    ),
    (
        'DIST003',
        'MedCare Pharma',
        'REG003',
        'DL-AP-003',
        '37MEDCA1234F1Z7',
        'Mahesh Reddy',
        'medcare@gmail.com',
        '9876543214',
        '9876543215',
        'Benz Circle',
        'Governorpet',
        'Vijayawada',
        'Andhra Pradesh',
        'India',
        '520010',
        'https://www.medcare.com',
        '2b3c4d5e-6f78-90ab-cdef-1234567890ab',
        true
    ),
    (
        'DIST004',
        'Sri Sai Pharma',
        'REG004',
        'DL-TG-004',
        '36SRISA1234F1Z8',
        'Suresh Rao',
        'srisai@gmail.com',
        '9876543216',
        '9876543217',
        'Main Road',
        'Tower Circle',
        'Karimnagar',
        'Telangana',
        'India',
        '505001',
        'https://www.srisaipharma.com',
        '3c4d5e6f-7890-abcd-ef12-34567890abcd',
        true
    ),
    (
        'DIST005',
        'Prime Healthcare',
        'REG005',
        'DL-TG-005',
        '36PRIME1234F1Z9',
        'Praveen Kumar',
        'prime@gmail.com',
        '9876543218',
        '9876543219',
        'Bus Stand Road',
        'Armoor',
        'Nizamabad',
        'Telangana',
        'India',
        '503001',
        'https://www.primehealth.com',
        '4d5e6f78-90ab-cdef-1234-567890abcdef',
        true
    ),
    (
        'DIST006',
        'Apollo Distributors',
        'REG006',
        'DL-TG-006',
        '36APOLL1234F1Z1',
        'Naveen Kumar',
        'apollo@gmail.com',
        '9876543220',
        '9876543221',
        'SD Road',
        'Paradise',
        'Secunderabad',
        'Telangana',
        'India',
        '500003',
        'https://www.apollodist.com',
        '5e6f7890-abcd-ef12-3456-7890abcdef12',
        true
    ),
    (
        'DIST007',
        'Care Medical Agencies',
        'REG007',
        'DL-TG-007',
        '36CAREM1234F1Z2',
        'Kiran Kumar',
        'caremedical@gmail.com',
        '9876543222',
        '9876543223',
        'Wyra Road',
        'Near Bus Stand',
        'Khammam',
        'Telangana',
        'India',
        '507001',
        'https://www.caremedical.com',
        '6f7890ab-cdef-1234-5678-90abcdef1234',
        true
    ),
    (
        'DIST008',
        'HealthPlus Pharma',
        'REG008',
        'DL-AP-008',
        '37HEALT1234F1Z3',
        'Vinod Kumar',
        'healthplus@gmail.com',
        '9876543224',
        '9876543225',
        'Lakshmipuram',
        'Brodipet',
        'Guntur',
        'Andhra Pradesh',
        'India',
        '522002',
        'https://www.healthplus.com',
        '7890abcd-ef12-3456-7890-abcdef123456',
        true
    ),
    (
        'DIST009',
        'MedLife Distributors',
        'REG009',
        'DL-AP-009',
        '37MEDLI1234F1Z4',
        'Rajesh Kumar',
        'medlife@gmail.com',
        '9876543226',
        '9876543227',
        'Beach Road',
        'MVP Colony',
        'Visakhapatnam',
        'Andhra Pradesh',
        'India',
        '530017',
        'https://www.medlife.com',
        '90abcdef-1234-5678-90ab-cdef12345678',
        true
    ),
    (
        'DIST010',
        'Global Pharma Traders',
        'REG010',
        'DL-AP-010',
        '37GLOBA1234F1Z5',
        'Srikanth Kumar',
        'global@gmail.com',
        '9876543228',
        '9876543229',
        'Air Bypass Road',
        'Balaji Colony',
        'Tirupati',
        'Andhra Pradesh',
        'India',
        '517501',
        'https://www.globalpharma.com',
        'abcdef12-3456-7890-abcd-ef1234567890',
        true
    )

) AS Source
(
    DistributorCode,
    DistributorName,
    RegistrationNumber,
    DrugLicenseNumber,
    GSTNumber,
    ContactPerson,
    Email,
    Phone,
    AlternatePhone,
    AddressLine1,
    AddressLine2,
    City,
    State,
    Country,
    PostalCode,
    Website,
    WarehouseId,  
    IsActive      
)

ON Target.DistributorCode = Source.DistributorCode

WHEN MATCHED THEN
UPDATE SET
    DistributorName      = Source.DistributorName,
    RegistrationNumber   = Source.RegistrationNumber,
    DrugLicenseNumber    = Source.DrugLicenseNumber,
    GSTNumber            = Source.GSTNumber,
    ContactPerson        = Source.ContactPerson,
    Email                = Source.Email,
    Phone                = Source.Phone,
    AlternatePhone       = Source.AlternatePhone,
    AddressLine1         = Source.AddressLine1,
    AddressLine2         = Source.AddressLine2,
    City                 = Source.City,
    State                = Source.State,
    Country              = Source.Country,
    PostalCode           = Source.PostalCode,
    Website              = Source.Website,
    WarehouseId          = Source.WarehouseId, 
    IsActive             = Source.IsActive,        
    ModifiedOn           = CURRENT_TIMESTAMP

WHEN NOT MATCHED THEN
INSERT
(
    DistributorCode,
    DistributorName,
    RegistrationNumber,
    DrugLicenseNumber,
    GSTNumber,
    ContactPerson,
    Email,
    Phone,
    AlternatePhone,
    AddressLine1,
    AddressLine2,
    City,
    State,
    Country,
    PostalCode,
    Website,
    WarehouseId, 
    IsActive,    
    CreatedOn
)
VALUES
(
    Source.DistributorCode,
    Source.DistributorName,
    Source.RegistrationNumber,
    Source.DrugLicenseNumber,
    Source.GSTNumber,
    Source.ContactPerson,
    Source.Email,
    Source.Phone,
    Source.AlternatePhone,
    Source.AddressLine1,
    Source.AddressLine2,
    Source.City,
    Source.State,
    Source.Country,
    Source.PostalCode,
    Source.Website,
    Source.WarehouseId,  
    Source.IsActive,  
    CURRENT_TIMESTAMP
);
