MERGE INTO Suppliers AS Target

USING
(
    VALUES
    (
        'SUP001',
        'Sun Pharma Distributors',
        'Ravi Kumar',
        'sunpharma@gmail.com',
        '9876500001',
        '9876501001',
        '36ABCDE1234F1Z5',
        'DL-TG-1001',
        'Road No.1',
        'Madhapur',
        'Hyderabad',
        'Telangana',
        'India',
        '500081',
        'https://www.sunpharma.com',
        TRUE
    ),
    (
        'SUP002',
        'Cipla Healthcare',
        'Ramesh Kumar',
        'cipla@gmail.com',
        '9876500002',
        '9876501002',
        '36ABCDE1234F1Z6',
        'DL-TG-1002',
        'MG Road',
        'Hanamkonda',
        'Warangal',
        'Telangana',
        'India',
        '506001',
        'https://www.cipla.com',
        TRUE
    ),
    (
        'SUP003',
        'Dr Reddy Laboratories',
        'Mahesh Reddy',
        'drreddy@gmail.com',
        '9876500003',
        '9876501003',
        '37ABCDE1234F1Z7',
        'DL-AP-1003',
        'Benz Circle',
        'Governorpet',
        'Vijayawada',
        'Andhra Pradesh',
        'India',
        '520010',
        'https://www.drreddys.com',
        TRUE
    ),
    (
        'SUP004',
        'Mankind Pharma',
        'Suresh Rao',
        'mankind@gmail.com',
        '9876500004',
        '9876501004',
        '36ABCDE1234F1Z8',
        'DL-TG-1004',
        'Main Road',
        'Tower Circle',
        'Karimnagar',
        'Telangana',
        'India',
        '505001',
        'https://www.mankindpharma.com',
        TRUE
    ),
    (
        'SUP005',
        'Alkem Laboratories',
        'Praveen Kumar',
        'alkem@gmail.com',
        '9876500005',
        '9876501005',
        '36ABCDE1234F1Z9',
        'DL-TG-1005',
        'Bus Stand Road',
        'Armoor',
        'Nizamabad',
        'Telangana',
        'India',
        '503001',
        'https://www.alkemlabs.com',
        TRUE
    ),
    (
        'SUP006',
        'Torrent Pharma',
        'Naveen Kumar',
        'torrent@gmail.com',
        '9876500006',
        '9876501006',
        '36ABCDE1234F2Z1',
        'DL-TG-1006',
        'SD Road',
        'Paradise',
        'Secunderabad',
        'Telangana',
        'India',
        '500003',
        'https://www.torrentpharma.com',
        TRUE
    ),
    (
        'SUP007',
        'Lupin Limited',
        'Kiran Kumar',
        'lupin@gmail.com',
        '9876500007',
        '9876501007',
        '36ABCDE1234F2Z2',
        'DL-TG-1007',
        'Wyra Road',
        'Near Bus Stand',
        'Khammam',
        'Telangana',
        'India',
        '507001',
        'https://www.lupin.com',
        TRUE
    ),
    (
        'SUP008',
        'Zydus Lifesciences',
        'Vinod Kumar',
        'zydus@gmail.com',
        '9876500008',
        '9876501008',
        '37ABCDE1234F2Z3',
        'DL-AP-1008',
        'Lakshmipuram',
        'Brodipet',
        'Guntur',
        'Andhra Pradesh',
        'India',
        '522002',
        'https://www.zyduslife.com',
        TRUE
    ),
    (
        'SUP009',
        'Glenmark Pharmaceuticals',
        'Rajesh Kumar',
        'glenmark@gmail.com',
        '9876500009',
        '9876501009',
        '37ABCDE1234F2Z4',
        'DL-AP-1009',
        'Beach Road',
        'MVP Colony',
        'Visakhapatnam',
        'Andhra Pradesh',
        'India',
        '530017',
        'https://www.glenmarkpharma.com',
        TRUE
    ),
    (
        'SUP010',
        'Abbott India',
        'Srikanth Kumar',
        'abbott@gmail.com',
        '9876500010',
        '9876501010',
        '37ABCDE1234F2Z5',
        'DL-AP-1010',
        'Air Bypass Road',
        'Balaji Colony',
        'Tirupati',
        'Andhra Pradesh',
        'India',
        '517501',
        'https://www.abbott.co.in',
        TRUE
    )

) AS Source
(
    SupplierCode,
    SupplierName,
    ContactPerson,
    Email,
    Phone,
    AlternatePhone,
    GSTNumber,
    DrugLicenseNumber,
    AddressLine1,
    AddressLine2,
    City,
    State,
    Country,
    PostalCode,
    Website,
    IsActive
)

ON Target.SupplierCode = Source.SupplierCode

WHEN MATCHED THEN
UPDATE SET
    SupplierName = Source.SupplierName,
    ContactPerson = Source.ContactPerson,
    Email = Source.Email,
    Phone = Source.Phone,
    AlternatePhone = Source.AlternatePhone,
    GSTNumber = Source.GSTNumber,
    DrugLicenseNumber = Source.DrugLicenseNumber,
    AddressLine1 = Source.AddressLine1,
    AddressLine2 = Source.AddressLine2,
    City = Source.City,
    State = Source.State,
    Country = Source.Country,
    PostalCode = Source.PostalCode,
    Website = Source.Website,
    IsActive = Source.IsActive,
    ModifiedOn = CURRENT_TIMESTAMP

WHEN NOT MATCHED THEN
INSERT
(
    SupplierCode,
    SupplierName,
    ContactPerson,
    Email,
    Phone,
    AlternatePhone,
    GSTNumber,
    DrugLicenseNumber,
    AddressLine1,
    AddressLine2,
    City,
    State,
    Country,
    PostalCode,
    Website,
    IsActive,
    CreatedOn
)
VALUES
(
    Source.SupplierCode,
    Source.SupplierName,
    Source.ContactPerson,
    Source.Email,
    Source.Phone,
    Source.AlternatePhone,
    Source.GSTNumber,
    Source.DrugLicenseNumber,
    Source.AddressLine1,
    Source.AddressLine2,
    Source.City,
    Source.State,
    Source.Country,
    Source.PostalCode,
    Source.Website,
    Source.IsActive,
    CURRENT_TIMESTAMP
);
